### ISSUE TITLE
sorting manytoone 

### ISSUE THREAD

**Issue by snuffer82** [symfony2admingenerator/GeneratorBundle#317] opened 2017-11-15 20:28 UTC
hi all,
I have a problem sorting a column in the list. The field I want to order is an external key and when I click it to order it I get an exception. 

```
AppBundle\Entity\TSchedaGenerale:
    type: entity
    table: t_scheda_generale
    indexes:
        fk_t_scheda_generale_t_tipo_evento1_idx:
            columns:
                - id_tipo_evento
      ...........................
    manyToOne:
        idTipoEvento:
            targetEntity: TTipoEvento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_evento:
                    referencedColumnName: id_tipo_evento
            orphanRemoval: false

```
this is the exception:

```
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT id_scheda_generale_0 FROM (SELECT t0_.id_scheda_generale AS id_scheda_generale_0, t0_.data_aa AS data_aa_1, t0_.data_mm AS data_mm_2, t0_.data_gg AS data_gg_3, t0_.codice_segnalazione AS codice_segnalazione_4, t0_.numero_esemplari AS numero_esemplari_5, t0_.ambiente AS ambiente_6, t0_.rilevatore AS rilevatore_7, t0_.note AS note_8, t0_.autore AS autore_9, t0_.phylum AS phylum_10, t0_.classe AS classe_11, t0_.ordine AS ordine_12, t0_.superfamily AS superfamily_13, t0_.family AS family_14, t0_.genus AS genus_15, t0_.subgenus AS subgenus_16, t0_.species AS species_17, t0_.infraspecies AS infraspecies_18 FROM t_scheda_generale t0_) dctrn_result ORDER BY t0_.id_tipo_evento ASC LIMIT 10 OFFSET 0':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0_.id_tipo_evento' in 'order clause'").
```

how can i fix the problem??

thanks a lot
paolo

**Comment by bobvandevijver** [comment] 2017-11-15 20:37
I cannot imagine you have an `id_tipo_evento` column in your `idTipoEvento` colums (or is it self-referencing). 

First check you database, because this error indicates that simply the column you want to sort on, is not available in the database. If it is an object, you should be able to change the sort column: see [the docs](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/doc/admin/builder-list.md) for that.

**Comment by snuffer82** [comment] 2017-11-15 20:53
thanks for quick support; this is the schema of the two related tables:

![schema](https://user-images.githubusercontent.com/17122286/32859390-a3cd4d08-ca4e-11e7-9c4f-98e5b8c6708a.png)

as you can see the field exists and it is not it self-referencing. 
where I'm wrong? thanks a lot
![screenshot_20171115_215258](https://user-images.githubusercontent.com/17122286/32859637-5d783e3e-ca4f-11e7-9426-321edd0e8b73.png)

**Comment by bobvandevijver** [comment] 2017-11-16 21:08
Right, after looking more carefully into the query you posted, it appears to be about the outer query (simplified all separate columns with a single `*`): 
```sql
SELECT DISTINCT id_scheda_generale_0 FROM 
  (SELECT * FROM t_scheda_generale t0_) 
dctrn_result 
ORDER BY t0_.id_tipo_evento ASC LIMIT 10 OFFSET 0'
```

As you can see, the query tries to order on a column which is not selected in the outer query.

This is actually a duplicate of #306, but unfortunately, we did not find a solution there. Can you try to debug this yourself? Can you also post your complete generator configuration and the generated twig template (you can find that one somewhere in `app/cache/dev/AdminGenerated/{bundlename}/Resources/views`.

**Comment by snuffer82** [comment] 2017-11-18 16:25
this is TSchedaGenerale-generator.yml

```
generator: admingenerator.generator.doctrine
params:
    model: AppBundle\Entity\TSchedaGenerale
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AppBundle
    pk_requirement: ~

    fields:
      dataGg:
        label: Data (gg)
      dataMm:
        label: Data (mm) 
      dataAa:
        label:  Data (aaaa) 
      idTipoEvento:
        label: Tipo Segnalazione
        #sort_on:  idTipoEvento
      codiceSegnalazione:
        label: Codice Segnalazione/Animale 
      numeroEsemplari:
        label: Numero Esemplari 
      rilevatore:
        label: Rilevatore  
      note:
        label: Note
              
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
        
builders:
    list:
        params:
            title: Elenco Segnalazioni
            display: [codiceSegnalazione, dataGg, dataMm, dataAa, idTipoEvento, ordine, species]
            actions:
                new: ~
                excel: ~
            object_actions:
                edit: ~
                delete: ~
                excel: ~
                show: ~
            batch_actions:
                delete: ~
            filters: [codiceSegnalazione, idTipoEvento, phylum, ordine, species, infraspecies ]        
            filtersMode: modal              
                  
    excel:
        params:
            display: ~
            filename: ~
            filetype: ~
            datetime_format: ~
            fields: ~
            export:  
                short:
                    #credentials:     'hasRole("ROLE_USER")'
                    show_button:     true
                    icon:            fa-files-o 
                    label:           Show report
                    filename:        Short-repot.xls
                    filetype:        Excel5
                    datetime_format: d.m.Y
                    fields:          
                        title:
                            label:   Product name
                    display:
                        -            codice_segnalazione
                        -            data_aa
                        -            autore            
                full:
                    #credentials:     'hasRole("ROLE_USER")'
                    show_button:     true
                    icon:            fa-files-o 
                    label:           Full report
                    filename:        full-report.xlsx
                    filetype:        Excel2007
                    datetime_format: Y-m-d H:i:s
                    display:
                        -            codice_segnalazione
                        -            data_aa
                        -            autore
    new:
        params:
            title: GESTIONE SCHEDA GENERALE
            display:
            tabs:
              "Dati Generali": 
                "_1": [codiceSegnalazione, idTipoEvento, [dataGg, dataMm, dataAa], numeroEsemplari, rilevatore,note]
              "Classificazione": 
                "_2": [[phylum, classe, ordine], [superfamily, family], [genus, subgenus], [species, infraspecies]]
              "Reperto": 
                "_3": [ ]
              "Upload": 
                "_4": [ ]
            actions:
                save: ~
                list: ~

                
    edit:
        params:
            title: GESTIONE SCHEDA GENERALE
            display:
            tabs:
              "Dati Generali": 
                "_1": [codiceSegnalazione, idTipoEvento, [dataGg, dataMm, dataAa], numeroEsemplari, rilevatore,note]
              "Classificazione": 
                "_2": [[phylum, classe, ordine], [superfamily, family], [genus, subgenus], [species, infraspecies]]
              "Reperto": 
                "_3": []
              "Upload": 
                "_4": [ ]
            actions:
                save: ~
                save-and-add: ~
                list: ~
                delete: ~

    show:
        params:
            title: GESTIONE SCHEDA GENERALE
            display: [codiceSegnalazione, dataGg, dataMm, dataAa, idTipoEvento, ordine, species]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
```
and this is my twig templates:
[http://www.edulink.uniud.it/download/twig_template/filters.html.twig](filters.html.twig)
[http://www.edulink.uniud.it/download/twig_template/index.html.twig](index.html.twig)
[http://www.edulink.uniud.it/download/twig_template/results.html.twig](results.html.twig)
[http://www.edulink.uniud.it/download/twig_template/row.html.twig](row.html.twig)

results.html.twig
 ```
   <div class="col-md-12 list-results-container no-filters">
            <div class="box box-primary">
            <div class="box-header list-header list-nb-results clearfix">    {% block list_nbresults %}
        <h3 class="box-title">
            {% block list_nbresults_text %}
                {% set count = TSchedaGenerales.nbResults %}
                {% set start = ( TSchedaGenerales.currentPage - 1 ) * TSchedaGenerales.maxPerPage + 1 %}
                {% set end = start + TSchedaGenerales.maxPerPage - 1 %}
                {% set end = end > count ? count : end %}

                {% if TSchedaGenerales.haveToPaginate %}
                {{ "list.display.range"|trans({'%start%': start,'%end%': end,'%count%': count,}, "Admingenerator")|raw }}
                {% elseif  count > 1  %}
                {{ "list.display.all"|trans({'%count%': count,}, "Admingenerator")|raw }}
                {% else %}
                {{ "list.display.one"|trans({'%count%': count,}, "Admingenerator")|raw }}
                {% endif %}
            {% endblock list_nbresults_text %}
        </h3>
    {% endblock list_nbresults %}
    {% set class = "" %}
    {% if app.session.get('\\AppBundle\\TSchedaGeneraleList\\Filters',{}) is empty %}
    {% set class = "disabled" %}
    {% endif %}
                <div class="box-tools pull-right">          
                  <button class="btn btn-sm btn-default" data-toggle="modal" data-target="#s2a_modal_filter_dialog">
                    <i class="fa fa-filter"></i> {{ "list.filters"|trans({}, "Admingenerator")|raw }}
                  </button>
                  <a href="{{ filtersUrl }}?reset=all" class="btn btn-sm btn-default {{ class }}">
                    <i class="fa fa-refresh"></i> {{ "list.button.reset"|trans({}, "Admingenerator")|raw }}
                  </a>                    
                </div><!-- /.box-tools -->
            </div>
                {% block form_batch_actions %}
                                <form id="form-list-tschedagenerale" method="post" class="form-list-batch" action="{{ path("AppBundle_TSchedaGenerale_batch") }}" role="form">
                <input type="hidden" value="{{ "AppBundle_TSchedaGenerale_batch"|csrf_token }}" name="_csrf_token" />
            {% endblock form_batch_actions %}

                <div class="box-body table-responsive no-padding list-results">
                    <table id="table-list-tschedagenerale" class="table table-hover object-actions-tschedagenerale">
                            {% block list_thead %}
    <thead>
        {% block list_thead_inner %}
                <tr role="row" class="list-results-fields-header">
                    <th class="list-results-fields-header-batch">
                <input id="batch_select_all" type="checkbox" name="batch_select_all" />
            </th>
                    {% block list_thead_column_codicesegnalazione %}        {% if (true) %}
        <th class="list-results-fields-header-column list-results-fields-header-column-codicesegnalazione{% if 1 %} sorting{% if sortColumn == 'codiceSegnalazione' and sortOrder == 'ASC' %}_asc{% elseif sortColumn == 'codiceSegnalazione' and sortOrder == 'DESC' %}_desc{% endif %}{% endif %}">
        {% if sortColumn == 'codiceSegnalazione' and sortOrder == 'ASC' %}
                <a href="{{ path(listRoute, { 'sort': 'codiceSegnalazione', 'order_by': 'desc'}) }}">
            {% else %}
                <a href="{{ path(listRoute, { 'sort': 'codiceSegnalazione', 'order_by': 'asc'}) }}">
            {% endif %}{{ 'Codice Segnalazione/Animale'|trans({}, 'Admin') }}</a>
        </th>
            {% endif %}
        {% endblock list_thead_column_codicesegnalazione %}

            {% block list_thead_column_datagg %}        {% if (true) %}
        <th class="list-results-fields-header-column list-results-fields-header-column-datagg{% if 1 %} sorting{% if sortColumn == 'dataGg' and sortOrder == 'ASC' %}_asc{% elseif sortColumn == 'dataGg' and sortOrder == 'DESC' %}_desc{% endif %}{% endif %}">
        {% if sortColumn == 'dataGg' and sortOrder == 'ASC' %}
                <a href="{{ path(listRoute, { 'sort': 'dataGg', 'order_by': 'desc'}) }}">
            {% else %}
                <a href="{{ path(listRoute, { 'sort': 'dataGg', 'order_by': 'asc'}) }}">
            {% endif %}{{ 'Data (gg)'|trans({}, 'Admin') }}</a>
        </th>
            {% endif %}
        {% endblock list_thead_column_datagg %}

            {% block list_thead_column_datamm %}        {% if (true) %}
        <th class="list-results-fields-header-column list-results-fields-header-column-datamm{% if 1 %} sorting{% if sortColumn == 'dataMm' and sortOrder == 'ASC' %}_asc{% elseif sortColumn == 'dataMm' and sortOrder == 'DESC' %}_desc{% endif %}{% endif %}">
        {% if sortColumn == 'dataMm' and sortOrder == 'ASC' %}
                <a href="{{ path(listRoute, { 'sort': 'dataMm', 'order_by': 'desc'}) }}">
            {% else %}
                <a href="{{ path(listRoute, { 'sort': 'dataMm', 'order_by': 'asc'}) }}">
            {% endif %}{{ 'Data (mm)'|trans({}, 'Admin') }}</a>
        </th>
            {% endif %}
        {% endblock list_thead_column_datamm %}

            {% block list_thead_column_dataaa %}        {% if (true) %}
        <th class="list-results-fields-header-column list-results-fields-header-column-dataaa{% if 1 %} sorting{% if sortColumn == 'dataAa' and sortOrder == 'ASC' %}_asc{% elseif sortColumn == 'dataAa' and sortOrder == 'DESC' %}_desc{% endif %}{% endif %}">
        {% if sortColumn == 'dataAa' and sortOrder == 'ASC' %}
                <a href="{{ path(listRoute, { 'sort': 'dataAa', 'order_by': 'desc'}) }}">
            {% else %}
                <a href="{{ path(listRoute, { 'sort': 'dataAa', 'order_by': 'asc'}) }}">
            {% endif %}{{ 'Data (aaaa)'|trans({}, 'Admin') }}</a>
        </th>
            {% endif %}
        {% endblock list_thead_column_dataaa %}

            {% block list_thead_column_idtipoevento %}        {% if (true) %}
        <th class="list-results-fields-header-column list-results-fields-header-column-idtipoevento{% if 1 %} sorting{% if sortColumn == 'idTipoEvento' and sortOrder == 'ASC' %}_asc{% elseif sortColumn == 'idTipoEvento' and sortOrder == 'DESC' %}_desc{% endif %}{% endif %}">
        {% if sortColumn == 'idTipoEvento' and sortOrder == 'ASC' %}
                <a href="{{ path(listRoute, { 'sort': 'idTipoEvento', 'order_by': 'desc'}) }}">
            {% else %}
                <a href="{{ path(listRoute, { 'sort': 'idTipoEvento', 'order_by': 'asc'}) }}">
            {% endif %}{{ 'Tipo Segnalazione'|trans({}, 'Admin') }}</a>
        </th>
            {% endif %}
        {% endblock list_thead_column_idtipoevento %}

            {% block list_thead_column_ordine %}        {% if (true) %}
        <th class="list-results-fields-header-column list-results-fields-header-column-ordine{% if 1 %} sorting{% if sortColumn == 'ordine' and sortOrder == 'ASC' %}_asc{% elseif sortColumn == 'ordine' and sortOrder == 'DESC' %}_desc{% endif %}{% endif %}">
        {% if sortColumn == 'ordine' and sortOrder == 'ASC' %}
                <a href="{{ path(listRoute, { 'sort': 'ordine', 'order_by': 'desc'}) }}">
            {% else %}
                <a href="{{ path(listRoute, { 'sort': 'ordine', 'order_by': 'asc'}) }}">
            {% endif %}{{ 'Ordine'|trans({}, 'Admin') }}</a>
        </th>
            {% endif %}
        {% endblock list_thead_column_ordine %}

            {% block list_thead_column_species %}        {% if (true) %}
        <th class="list-results-fields-header-column list-results-fields-header-column-species{% if 1 %} sorting{% if sortColumn == 'species' and sortOrder == 'ASC' %}_asc{% elseif sortColumn == 'species' and sortOrder == 'DESC' %}_desc{% endif %}{% endif %}">
        {% if sortColumn == 'species' and sortOrder == 'ASC' %}
                <a href="{{ path(listRoute, { 'sort': 'species', 'order_by': 'desc'}) }}">
            {% else %}
                <a href="{{ path(listRoute, { 'sort': 'species', 'order_by': 'asc'}) }}">
            {% endif %}{{ 'Species'|trans({}, 'Admin') }}</a>
        </th>
            {% endif %}
        {% endblock list_thead_column_species %}

                {% block list_thead_actions %}
            <th class="list-results-fields-header-objectactions">{{ "list.header.actions"|trans({}, "Admingenerator")|raw }}</th>
        {% endblock list_thead_actions %}
        </tr>

        {% endblock list_thead_inner %}
    </thead>
    {% endblock list_thead %}

                            {% block list_tbody %}
        <tbody>
            {% block list_tbody_rows %}
                {% if TSchedaGenerales is not empty %}
                    {% for TSchedaGenerale in TSchedaGenerales %}
                        {% include "AppBundle:TSchedaGeneraleList:row.html.twig" with {  } %}
                    {% endfor %}
                {% else %}
                    <tr role="row" class="list-results-fields-row list-results-fields-row-noresults">
                        <td colspan="999">{{ "list.no.results"|trans({}, "Admingenerator")|raw }}</td>
                    </tr>
                {% endif %}
            {% endblock list_tbody_rows %}
        </tbody>
    {% endblock list_tbody %}
        {% block object_actions_script_container %}
    <script type="application/javascript">
        {% block object_actions_script_inner %}
        window.S2A = window.S2A || {};
        window.S2A.singleActionsAdminOptions = {
            containerSelector: 'section.content',
            buttonSelector: '.object-action'
        };
        {% endblock object_actions_script_inner %}
    </script>
    {% endblock object_actions_script_container %}


                    </table>
                </div>
                <div class="box-footer list-footer">
                        {% block list_footer %}
        <div class="row">
            <div class="list-results-actions">
                {% block batch_actions_wrapper %}
                                            <div class="list-results-actions-batch col-md-4" role="batch-actions">
                                {% block batch_actions %}
                    
                            {% set actionCredentials = [ 'AdmingenAllowed' ] %}
                {% if is_one_admingenerator_granted(actionCredentials) %}
                            <div class="input-group">
                    <select name="action" class="form-control">
                        <option selected="selected" value="none">{{ "batch.list.selected"|trans({}, "Admingenerator")|raw }}</option>
                                                    {% block batch_action_delete %}
                                                            {% if (true) %}
                                                                    <option
        value="delete"            data-confirm="{{ "action.batch.delete.confirm"|trans({}, "Admingenerator")|escape("html_attr") }}"
            data-confirm-modal="#confirmBatchModal"
            data-toggle="modal"
        >
            <i class="fa fa-times"></i>             {{ "action.batch.delete.label"|trans({}, "Admingenerator")|raw }}
    </option>

                                                            {% endif %}
                                                        {% endblock batch_action_delete %}
                                            </select>
                    <span class="input-group-btn">
                        <button type="submit" name="batch" class="btn btn-warning" title="{{ "batch.list.send"|trans({}, "Admingenerator")|escape("html_attr") }}">
                            {{ "batch.list.send"|trans({}, "Admingenerator")|raw }}
                        </button>
                    </span>
                </div>
                            {% endif %}
                        {% endblock batch_actions %}

                                {% block batch_actions_script_container %}
    <script type="application/javascript">
        {% block batch_actions_script_inner %}
        window.S2A = window.S2A || {};
        window.S2A.batchActionsAdminOptions = {
            containerSelector: '.form-list-batch',
            actionSelector: 'select[name=action]',
            toggleSelector: 'input[name=batch_select_all]',
            elementSelector: '.list-results-fields-row-batch-selector',
            noActionValue: 'none',
            noElementsSelectedMessage: '{{ "batch.list.none.selected"|trans({}, "Admingenerator")|escape("js") }}'
        };
        {% endblock batch_actions_script_inner %}
    </script>
    {% endblock batch_actions_script_container %}

                        </div>
                    {% endblock batch_actions_wrapper %}
                {% block generic_actions_wrapper %}
                                            <div class="list-results-actions-generic col-md-8 text-right" role="generic-actions">
                                {% block generic_actions %}
                            {% block pre_generic_actions %}{% endblock pre_generic_actions %}
                
                                    {% set actionCredentials = [ 'AdmingenAllowed' ] %}
                    {% if is_one_admingenerator_granted(actionCredentials, (TSchedaGenerale is defined) ? TSchedaGenerale : null ) %}
                
                                                    {% block generic_action_new %}
                                            {% if (true) %}
                    
                    
                                    
            <a class="generic-action btn btn-primary" href="{{ path("AppBundle_TSchedaGenerale_new", {}) }}"><i class="fa fa-fw fa-plus"></i> {{ "action.generic.new"|trans({}, "Admingenerator")|raw }}
        </a>
    

                    
                                            {% endif %}
                                        {% endblock generic_action_new %}
                                    {% block generic_action_excel %}
                                            {% if (true) %}
                    
                    
                                    
        <div class="btn-group">
           <button type="button" class="generic-action btn btn-info" data-toggle="dropdown" aria-expanded="false">
              <i class="fa fa-fw fa-file-excel-o"></i> {{ "action.generic.export"|trans({}, "Admingenerator")|raw }} 
              <span class="caret"></span>
           </button>
           <ul class="dropdown-menu dropdown-menu-right" role="menu">
              <li><a class="generic-action btn btn-info" href="{{ path("AppBundle_TSchedaGenerale_excel", {}) }}"><i class="fa fa-fw fa-file-excel-o"></i> {{ "action.generic.excel"|trans({}, "Admingenerator")|raw }}</a></li>
    
    
                {% if (true) %}
      
        <li><a class="generic-action btn btn-info" href="{{ path("AppBundle_TSchedaGenerale_excel", { key: 'short' }) }}"><i class="fa fa-fw fa-files-o"></i> {{ "Show report"|trans({}, "Admingenerator")|raw }}
        </a></li>

                {% endif %}
      
    
                {% if (true) %}
      
        <li><a class="generic-action btn btn-info" href="{{ path("AppBundle_TSchedaGenerale_excel", { key: 'full' }) }}"><i class="fa fa-fw fa-files-o"></i> {{ "Full report"|trans({}, "Admingenerator")|raw }}
        </a></li>

                {% endif %}
      
                    
           </ul>
        </div>
                


                    
                                            {% endif %}
                                        {% endblock generic_action_excel %}
                
                                    {% endif %}
                                {% block post_generic_actions %}{% endblock post_generic_actions %}
                {% endblock generic_actions %}
    {% block generic_actions_script_container %}
    <script type="application/javascript">
        {% block generic_actions_script_inner %}
        window.S2A = window.S2A || {};
        window.S2A.genericActionsAdminOptions = {
            containerSelector: 'section.content',
            buttonSelector: '.generic-action'
        };
        {% endblock generic_actions_script_inner %}
    </script>
    {% endblock generic_actions_script_container %}

                        </div>
                    {% endblock generic_actions_wrapper %}
            </div>
        </div>
        <div class="row">
            {% block pagination_wrapper %}
                <div class="list-results-pagination">
                        <div class="list-results-pagination-pages col-md-8">
            {% block list_paginator_pages %}
        {% if TSchedaGenerales.haveToPaginate %}
            {{ pagerfanta(TSchedaGenerales, 'admingenerator', {css_custom_class: 'no-margin pull-right'}) }}
        {% endif %}
    {% endblock list_paginator_pages %}

    </div>
    <div class="list-results-pagination-perpage col-md-4">
            {% block list_paginator_perpage %}
        {% if TSchedaGenerales.haveToPaginate or TSchedaGenerales.maxPerPage is not same as(perPageChoices|first) %}
            <div class="btn-group dropup pull-right">
                <div class="btn btn-sm btn-default btn-reset">{{ "pagerfanta.view.perpage"|trans({}, "Admingenerator")|raw }}</div>
                <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown">
                    {{ "pagerfanta.num.elements"|trans({"%number%": TSchedaGenerales.maxPerPage}, "Admingenerator") }} <span class="caret"></span>
                </button>
                <ul class="dropdown-menu  dropdown-menu-right" role="perpage">
                    {% for perPage in perPageChoices %}
                    <li>
                        {% block list_paginator_perpage_link %}
                            <a href="{{ path("AppBundle_TSchedaGenerale_list", {perPage: perPage}) }}">
                                {{ "pagerfanta.num.elements"|trans({"%number%": perPage}, "Admingenerator") }}
                            </a>
                        {% endblock list_paginator_perpage_link %}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endblock list_paginator_perpage %}

    </div>

                </div>
            {% endblock pagination_wrapper %}
        </div>
    {% endblock list_footer %}

                </div>
                {% block endform_batch_actions %}
                    </form>
            {% endblock endform_batch_actions %}

        </div>
    </div>

```

Any suggestion is well appreciated!!
thanks

**Comment by bobvandevijver** [comment] 2017-11-18 16:28
Do you know which line in the templates throws the exception?

**Comment by bobvandevijver** [comment] 2017-11-18 17:02
Right, I think I found your problem: can you try to adjust your generator configuration with the snippet below?

```
generator: admingenerator.generator.doctrine
params:
    fields:
      idTipoEvento:
        sortOn:  idTipoEvento.id_tipo_evento
```

As you are sorting on a object, you are required to specify on which column of that object you want to actually sort: this is not done automatically. (also mentioned [here](https://github.com/symfony2admingenerator/GeneratorBundle/blob/d6ffae6fcc863dbaa9ff8aa39cbfd9c8af3286c3/Resources/doc/admin/fields.md#sort-on).

**Comment by snuffer82** [comment] 2017-11-19 09:28
thanks a lot!!! I have modify a little bit your suggestion and it works!!

```
      idTipoEvento:
        label: Tipo Segnalazione
        sortOn:  idTipoEvento.idTipoEvento
```
I really appreciate your help
Paolo

**Comment by bobvandevijver** [comment] 2017-11-19 10:37
Great, you're welcome!

**Closed by bobvandevijver** 2017-11-19 10:37 UTC
Labels: awaiting feedback, question
