### ISSUE TITLE
Undefined index: access

### ISSUE THREAD

**Issue by atamashi** [symfony2admingenerator/GeneratorBundle#209] opened 2015-09-08 17:08 UTC
I'm working with windows 7 and PHP 5.5.28. I installed and configured the package and all its requirements. But when I run in localhost even load, it fails to create logs, and throws me this message:
Symfony\Component\Debug\Exception\ContextErrorException Notice: Undefined index: access
In my AppBundle not use that term as an index. Looking to sublimetext found that the access index is used in css files that are generated as suggested by instalorlo.

**Comment by bobvandevijver** [comment] 2015-09-08 18:12
As far as I know, we do not use `access` in a index-way, which means that you probably made a mistake somewhere else and it is not related to the admingenerator. 

You should check which file contains the notice. You can also disable debug to see if that helps, it might be that another bundle (/dependency) is causing the problem.

**Comment by atamashi** [comment] 2015-09-08 19:20
ok, tthankyou, very good!

**Comment by atamashi** [comment] 2015-09-10 14:32
Indeed, I found the package that the problem is related. And I put the question on Stackoverflow. Help me please.
For more information sent to the console the command like this:

php app/console cache:clear --no-debug
and from the information I receive it says:

Notice: Undefined index: access in D:\Applications\neucengestion\vendor\jms\ security-extra-bundle\JMS\SecurityExtraBundle\DependencyInjection\ SecurityExtension.php on line 110

Reviewing the code of SecurityExtension meeting that runs through the access control to implement security. I missing? could someone please direct me to handle this case? Thank you!

**Comment by bobvandevijver** [comment] 2015-10-27 09:55
Closing this as the problem is not related to the AdminGenerator. Did you manage to solve it?

**Closed by bobvandevijver** 2015-10-27 09:55 UTC
